///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addFloors recording.
    /// </summary>
    [TestModule("66db7218-ae63-452d-8dec-213f3ff88fb7", ModuleType.Recording, 1)]
    public partial class addFloors : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static addFloors instance = new addFloors();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public addFloors()
        {
            floorName = "";
            departmentName = "";
            optionIndex = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static addFloors Instance
        {
            get { return instance; }
        }

#region Variables

        string _floorName;

        /// <summary>
        /// Gets or sets the value of variable floorName.
        /// </summary>
        [TestVariable("f013852e-4554-406d-8a26-ab25f9aac33f")]
        public string floorName
        {
            get { return _floorName; }
            set { _floorName = value; }
        }

        string _departmentName;

        /// <summary>
        /// Gets or sets the value of variable departmentName.
        /// </summary>
        [TestVariable("ae453e25-33a2-40d3-b4c4-8ae438857842")]
        public string departmentName
        {
            get { return _departmentName; }
            set { _departmentName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable optionIndex.
        /// </summary>
        [TestVariable("4d8f2ce5-47f1-4000-9013-c4befb87fbb9")]
        public string optionIndex
        {
            get { return repo.optionIndex; }
            set { repo.optionIndex = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floors_FloorName' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floors_FloorNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.building_createEditFloors.floors_FloorName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$floorName' with focus on 'ApplicationUnderTest.building_createEditFloors.floors_FloorName'.", repo.ApplicationUnderTest.building_createEditFloors.floors_FloorNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.building_createEditFloors.floors_FloorName.PressKeys(floorName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floors_Description' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floors_DescriptionInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.building_createEditFloors.floors_Description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'floorDescription' with focus on 'ApplicationUnderTest.building_createEditFloors.floors_Description'.", repo.ApplicationUnderTest.building_createEditFloors.floors_DescriptionInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.building_createEditFloors.floors_Description.PressKeys("floorDescription");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floors_createDepartmentIcon' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floors_createDepartmentIconInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.building_createEditFloors.floors_createDepartmentIcon.Click();
            //Delay.Milliseconds(0);
            
            //HelperMethodsCollection.waitForLoading();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_DepartmentName' at Center.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_DepartmentNameInfo, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_DepartmentName.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$departmentName' with focus on 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_DepartmentName'.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_DepartmentNameInfo, new RecordItemIndex(7));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_DepartmentName.PressKeys(departmentName);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_Color' at Center.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_ColorInfo, new RecordItemIndex(8));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_Color.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test color' with focus on 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_Color'.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_ColorInfo, new RecordItemIndex(9));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_Color.PressKeys("test color");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_No' at Center.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_NoInfo, new RecordItemIndex(10));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_No.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8378' with focus on 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_No'.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_NoInfo, new RecordItemIndex(11));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_No.PressKeys("8378");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_Floor_CreateEditDepartment.department_ButtonTagSave' at Center.", repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_ButtonTagSaveInfo, new RecordItemIndex(12));
            //repo.ApplicationUnderTest.building_Floor_CreateEditDepartment.department_ButtonTagSave.Click();
            //Delay.Milliseconds(0);
            
            //HelperMethodsCollection.waitForLoading();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floors_Department' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floors_DepartmentInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.building_createEditFloors.floors_Department.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floorsDepartmentDropdown_searchBar' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floorsDepartmentDropdown_searchBarInfo, new RecordItemIndex(15));
            //repo.ApplicationUnderTest.building_createEditFloors.floorsDepartmentDropdown_searchBar.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$departmentName' with focus on 'ApplicationUnderTest.building_createEditFloors.floorsDepartmentDropdown_searchBar'.", repo.ApplicationUnderTest.building_createEditFloors.floorsDepartmentDropdown_searchBarInfo, new RecordItemIndex(16));
            //repo.ApplicationUnderTest.building_createEditFloors.floorsDepartmentDropdown_searchBar.PressKeys(departmentName);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'innertext' from item 'ApplicationUnderTest.building_createEditFloors.floors_visibleDropdown_firstInstance' and assigning its value to variable 'departmentName'.", repo.ApplicationUnderTest.building_createEditFloors.floors_visibleDropdown_firstInstanceInfo, new RecordItemIndex(17));
            departmentName = repo.ApplicationUnderTest.building_createEditFloors.floors_visibleDropdown_firstInstance.Element.GetAttributeValueText("innertext");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floors_visibleDropdown_firstInstance' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floors_visibleDropdown_firstInstanceInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.building_createEditFloors.floors_visibleDropdown_firstInstance.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.building_createEditFloors.floors_headerDepartment' at Center.", repo.ApplicationUnderTest.building_createEditFloors.floors_headerDepartmentInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.building_createEditFloors.floors_headerDepartment.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
