///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createRoom_MDC recording.
    /// </summary>
    [TestModule("425253a1-e216-4af8-a7f9-2fe675bbc936", ModuleType.Recording, 1)]
    public partial class createRoom_MDC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static createRoom_MDC instance = new createRoom_MDC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createRoom_MDC()
        {
            itemCount = "";
            newTemplateName = "";
            roomNumber = "";
            roomFloor = "";
            roomDepartment = "";
            roomBuilding = "";
            roomDescription = "";
            optionIndex = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createRoom_MDC Instance
        {
            get { return instance; }
        }

#region Variables

        string _itemCount;

        /// <summary>
        /// Gets or sets the value of variable itemCount.
        /// </summary>
        [TestVariable("c2b3d699-6411-4196-83c5-0339ae3455f8")]
        public string itemCount
        {
            get { return _itemCount; }
            set { _itemCount = value; }
        }

        string _roomNumber;

        /// <summary>
        /// Gets or sets the value of variable roomNumber.
        /// </summary>
        [TestVariable("ec544dd9-1c54-4b47-a7c4-ebe5028e2755")]
        public string roomNumber
        {
            get { return _roomNumber; }
            set { _roomNumber = value; }
        }

        string _roomFloor;

        /// <summary>
        /// Gets or sets the value of variable roomFloor.
        /// </summary>
        [TestVariable("7fdf098d-4be6-4958-8387-915918b84de9")]
        public string roomFloor
        {
            get { return _roomFloor; }
            set { _roomFloor = value; }
        }

        string _roomDepartment;

        /// <summary>
        /// Gets or sets the value of variable roomDepartment.
        /// </summary>
        [TestVariable("ef2a8cfd-6f4d-47e2-a7dd-7c90fb55ed6d")]
        public string roomDepartment
        {
            get { return _roomDepartment; }
            set { _roomDepartment = value; }
        }

        string _roomBuilding;

        /// <summary>
        /// Gets or sets the value of variable roomBuilding.
        /// </summary>
        [TestVariable("a77c7f8c-de08-4a71-9af9-7f1a90f2d6cc")]
        public string roomBuilding
        {
            get { return _roomBuilding; }
            set { _roomBuilding = value; }
        }

        string _roomDescription;

        /// <summary>
        /// Gets or sets the value of variable roomDescription.
        /// </summary>
        [TestVariable("905ec7de-fe2b-4d53-a64f-6b27061f250d")]
        public string roomDescription
        {
            get { return _roomDescription; }
            set { _roomDescription = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable optionIndex.
        /// </summary>
        [TestVariable("268cc430-598f-4938-9922-3d14151368dd")]
        public string optionIndex
        {
            get { return repo.optionIndex; }
            set { repo.optionIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable newTemplateName.
        /// </summary>
        [TestVariable("d201279a-bf83-4427-83a7-d6e09baffd77")]
        public string newTemplateName
        {
            get { return repo.newTemplateName; }
            set { repo.newTemplateName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            itemCount = ValueConverter.ToString(HelperMethodsCollection.getNumberOfRecordsFromFooter(repo.ApplicationUnderTest.showingNumberOfRecords));
            Delay.Milliseconds(0);
            
            newTemplateName = HelperMethodsCollection.getNewCreateItem(ValueConverter.ArgumentFromString<int>("nextCount", itemCount), "category");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.addRoomButtonTag' at Center.", repo.ApplicationUnderTest.addRoomButtonTagInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.addRoomButtonTag.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_RoomName' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_RoomNameInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.roomCreateEditPage.room_RoomName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$newTemplateName' with focus on 'ApplicationUnderTest.roomCreateEditPage.room_RoomName'.", repo.ApplicationUnderTest.roomCreateEditPage.room_RoomNameInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.roomCreateEditPage.room_RoomName.PressKeys(newTemplateName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_BuildingDropdown' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_BuildingDropdownInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.roomCreateEditPage.room_BuildingDropdown.Click();
            Delay.Milliseconds(0);
            
            optionIndex = ValueConverter.ToString(HelperMethodsCollection.getDifferentOption(repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'innertext' from item 'ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic' and assigning its value to variable 'roomBuilding'.", repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamicInfo, new RecordItemIndex(9));
            roomBuilding = repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic.Element.GetAttributeValueText("innertext");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamicInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_BuildingDropdown' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_BuildingDropdownInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.roomCreateEditPage.room_BuildingDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_RoomNumber' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_RoomNumberInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.roomCreateEditPage.room_RoomNumber.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$roomNumber' with focus on 'ApplicationUnderTest.roomCreateEditPage.room_RoomNumber'.", repo.ApplicationUnderTest.roomCreateEditPage.room_RoomNumberInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.roomCreateEditPage.room_RoomNumber.PressKeys(roomNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_FloorDropdown' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_FloorDropdownInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.roomCreateEditPage.room_FloorDropdown.Click();
            Delay.Milliseconds(0);
            
            optionIndex = ValueConverter.ToString(HelperMethodsCollection.getDifferentOption(repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown));
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Get Value", "(Optional Action)\r\nGetting attribute 'innertext' from item 'ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic' and assigning its value to variable 'roomFloor'.", repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamicInfo, new RecordItemIndex(17));
                roomFloor = repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic.Element.GetAttributeValueText("innertext");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamicInfo, new RecordItemIndex(18));
                repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(18)); }
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_FloorDropdown' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_FloorDropdownInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.roomCreateEditPage.room_FloorDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_DepartmentDropdown' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_DepartmentDropdownInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.roomCreateEditPage.room_DepartmentDropdown.Click();
            Delay.Milliseconds(0);
            
            optionIndex = ValueConverter.ToString(HelperMethodsCollection.getDifferentOption(repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown));
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Get Value", "(Optional Action)\r\nGetting attribute 'innertext' from item 'ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic' and assigning its value to variable 'roomDepartment'.", repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamicInfo, new RecordItemIndex(23));
                roomDepartment = repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic.Element.GetAttributeValueText("innertext");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(23)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamicInfo, new RecordItemIndex(24));
                repo.ApplicationUnderTest.roomCreateEditPage.room_visibleDropdown_dynamic.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(24)); }
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_DepartmentDropdown' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_DepartmentDropdownInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.roomCreateEditPage.room_DepartmentDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.roomCreateEditPage.room_Description' at Center.", repo.ApplicationUnderTest.roomCreateEditPage.room_DescriptionInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.roomCreateEditPage.room_Description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$roomDescription' with focus on 'ApplicationUnderTest.roomCreateEditPage.room_Description'.", repo.ApplicationUnderTest.roomCreateEditPage.room_DescriptionInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.roomCreateEditPage.room_Description.PressKeys(roomDescription);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.buttonTagSubmit' at Center.", repo.ApplicationUnderTest.buttonTagSubmitInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.buttonTagSubmit.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
