///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createProjects_AllFields_AssociatedOrganization recording.
    /// </summary>
    [TestModule("dbfbc943-bc71-4083-8eab-0c8dc23ec3fb", ModuleType.Recording, 1)]
    public partial class createProjects_AllFields_AssociatedOrganization : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static createProjects_AllFields_AssociatedOrganization instance = new createProjects_AllFields_AssociatedOrganization();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createProjects_AllFields_AssociatedOrganization()
        {
            AE_Organization = "";
            AE_PrimaryContact = "";
            AE_SecondaryContact = "";
            CM_Organization = "";
            CM_PrimaryContact = "";
            CM_SecondaryContact = "";
            vendorOrganization = "";
            clientOrganization = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createProjects_AllFields_AssociatedOrganization Instance
        {
            get { return instance; }
        }

#region Variables

        string _AE_Organization;

        /// <summary>
        /// Gets or sets the value of variable AE_Organization.
        /// </summary>
        [TestVariable("c96ef05d-2e55-4627-b78a-52beff700d7f")]
        public string AE_Organization
        {
            get { return _AE_Organization; }
            set { _AE_Organization = value; }
        }

        string _AE_PrimaryContact;

        /// <summary>
        /// Gets or sets the value of variable AE_PrimaryContact.
        /// </summary>
        [TestVariable("0fd43b2f-daf2-4a38-a5ea-3f920b6e5e27")]
        public string AE_PrimaryContact
        {
            get { return _AE_PrimaryContact; }
            set { _AE_PrimaryContact = value; }
        }

        string _AE_SecondaryContact;

        /// <summary>
        /// Gets or sets the value of variable AE_SecondaryContact.
        /// </summary>
        [TestVariable("981be6ff-5aca-4a0b-bef3-a19c1ccf85f0")]
        public string AE_SecondaryContact
        {
            get { return _AE_SecondaryContact; }
            set { _AE_SecondaryContact = value; }
        }

        string _CM_Organization;

        /// <summary>
        /// Gets or sets the value of variable CM_Organization.
        /// </summary>
        [TestVariable("99db498c-7ffc-4d60-8a2a-7d382e095886")]
        public string CM_Organization
        {
            get { return _CM_Organization; }
            set { _CM_Organization = value; }
        }

        string _CM_PrimaryContact;

        /// <summary>
        /// Gets or sets the value of variable CM_PrimaryContact.
        /// </summary>
        [TestVariable("7a2cea9e-b677-4b47-b95b-6b543ed7857a")]
        public string CM_PrimaryContact
        {
            get { return _CM_PrimaryContact; }
            set { _CM_PrimaryContact = value; }
        }

        string _CM_SecondaryContact;

        /// <summary>
        /// Gets or sets the value of variable CM_SecondaryContact.
        /// </summary>
        [TestVariable("ba110920-76f1-40ba-b30b-54b58e133300")]
        public string CM_SecondaryContact
        {
            get { return _CM_SecondaryContact; }
            set { _CM_SecondaryContact = value; }
        }

        string _vendorOrganization;

        /// <summary>
        /// Gets or sets the value of variable vendorOrganization.
        /// </summary>
        [TestVariable("22e11ada-14ed-41f4-927c-2c698b2112c6")]
        public string vendorOrganization
        {
            get { return _vendorOrganization; }
            set { _vendorOrganization = value; }
        }

        string _clientOrganization;

        /// <summary>
        /// Gets or sets the value of variable clientOrganization.
        /// </summary>
        [TestVariable("8842d0d5-0ae2-48d4-9858-22ff8ef8e2a2")]
        public string clientOrganization
        {
            get { return _clientOrganization; }
            set { _clientOrganization = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv'.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.SelfInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.Self.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_OrganisationDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_OrganisationDropdownInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_OrganisationDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.AE_OrganisationDropdown_dynamic' and assigning its value to variable 'AE_Organization'.", repo.ApplicationUnderTest.AE_OrganisationDropdown_dynamicInfo, new RecordItemIndex(2));
            AE_Organization = repo.ApplicationUnderTest.AE_OrganisationDropdown_dynamic.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AE_OrganisationDropdown_dynamic' at Center.", repo.ApplicationUnderTest.AE_OrganisationDropdown_dynamicInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.AE_OrganisationDropdown_dynamic.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_OrganisationDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_OrganisationDropdownInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_OrganisationDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_PrimaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_PrimaryContactDropdownInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_PrimaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.AE_PrimaryContactDropdown_dynamic' and assigning its value to variable 'AE_PrimaryContact'.", repo.ApplicationUnderTest.AE_PrimaryContactDropdown_dynamicInfo, new RecordItemIndex(7));
            AE_PrimaryContact = repo.ApplicationUnderTest.AE_PrimaryContactDropdown_dynamic.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AE_PrimaryContactDropdown_dynamic' at Center.", repo.ApplicationUnderTest.AE_PrimaryContactDropdown_dynamicInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.AE_PrimaryContactDropdown_dynamic.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_PrimaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_PrimaryContactDropdownInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_PrimaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_SecondaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_SecondaryContactDropdownInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_SecondaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.AE_SecondaryContactDropdown_dynamic' and assigning its value to variable 'AE_SecondaryContact'.", repo.ApplicationUnderTest.AE_SecondaryContactDropdown_dynamicInfo, new RecordItemIndex(12));
            AE_SecondaryContact = repo.ApplicationUnderTest.AE_SecondaryContactDropdown_dynamic.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AE_SecondaryContactDropdown_dynamic' at Center.", repo.ApplicationUnderTest.AE_SecondaryContactDropdown_dynamicInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.AE_SecondaryContactDropdown_dynamic.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_SecondaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_SecondaryContactDropdownInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.AE_SecondaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_OrganizationDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_OrganizationDropdownInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_OrganizationDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.CM_OrganizationDropdown_dynamic' and assigning its value to variable 'CM_Organization'.", repo.ApplicationUnderTest.CM_OrganizationDropdown_dynamicInfo, new RecordItemIndex(17));
            CM_Organization = repo.ApplicationUnderTest.CM_OrganizationDropdown_dynamic.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CM_OrganizationDropdown_dynamic' at Center.", repo.ApplicationUnderTest.CM_OrganizationDropdown_dynamicInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.CM_OrganizationDropdown_dynamic.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_OrganizationDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_OrganizationDropdownInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_OrganizationDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_PrimaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_PrimaryContactDropdownInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_PrimaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.CM_PrimaryContactDropdown_dynamic' and assigning its value to variable 'CM_PrimaryContact'.", repo.ApplicationUnderTest.CM_PrimaryContactDropdown_dynamicInfo, new RecordItemIndex(22));
            CM_PrimaryContact = repo.ApplicationUnderTest.CM_PrimaryContactDropdown_dynamic.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CM_PrimaryContactDropdown_dynamic' at Center.", repo.ApplicationUnderTest.CM_PrimaryContactDropdown_dynamicInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.CM_PrimaryContactDropdown_dynamic.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_PrimaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_PrimaryContactDropdownInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_PrimaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_SecondaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_SecondaryContactDropdownInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_SecondaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.CM_SecondaryContactDropdown_options' and assigning its value to variable 'CM_SecondaryContact'.", repo.ApplicationUnderTest.CM_SecondaryContactDropdown_optionsInfo, new RecordItemIndex(27));
            CM_SecondaryContact = repo.ApplicationUnderTest.CM_SecondaryContactDropdown_options.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.CM_SecondaryContactDropdown_options' at Center.", repo.ApplicationUnderTest.CM_SecondaryContactDropdown_optionsInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.CM_SecondaryContactDropdown_options.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_SecondaryContactDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_SecondaryContactDropdownInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.CM_SecondaryContactDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.vendorOrganizationDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.vendorOrganizationDropdownInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.vendorOrganizationDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.vendorOrganizationDropdown_options' and assigning its value to variable 'vendorOrganization'.", repo.ApplicationUnderTest.vendorOrganizationDropdown_optionsInfo, new RecordItemIndex(32));
            vendorOrganization = repo.ApplicationUnderTest.vendorOrganizationDropdown_options.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.vendorOrganizationDropdown_options' at Center.", repo.ApplicationUnderTest.vendorOrganizationDropdown_optionsInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.vendorOrganizationDropdown_options.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.projects_Form.associatedOrganisationDiv.clientOrganizationDropdown' at Center.", repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.clientOrganizationDropdownInfo, new RecordItemIndex(34));
            repo.ApplicationUnderTest.projects_Form.associatedOrganisationDiv.clientOrganizationDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.clientOrganizationDropdown_options' and assigning its value to variable 'clientOrganization'.", repo.ApplicationUnderTest.clientOrganizationDropdown_optionsInfo, new RecordItemIndex(35));
            clientOrganization = repo.ApplicationUnderTest.clientOrganizationDropdown_options.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.clientOrganizationDropdown_options' at Center.", repo.ApplicationUnderTest.clientOrganizationDropdown_optionsInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.clientOrganizationDropdown_options.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
