///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The createCampus_MDC recording.
    /// </summary>
    [TestModule("cd11410d-0ddf-44d5-b79b-186c01c0647a", ModuleType.Recording, 1)]
    public partial class createCampus_MDC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static createCampus_MDC instance = new createCampus_MDC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public createCampus_MDC()
        {
            description = "";
            selectedCampus = "";
            selectedZone = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static createCampus_MDC Instance
        {
            get { return instance; }
        }

#region Variables

        string _description;

        /// <summary>
        /// Gets or sets the value of variable description.
        /// </summary>
        [TestVariable("5cfc5d97-1fd1-4d48-b369-170f2f681c4f")]
        public string description
        {
            get { return _description; }
            set { _description = value; }
        }

        string _selectedCampus;

        /// <summary>
        /// Gets or sets the value of variable selectedCampus.
        /// </summary>
        [TestVariable("5ca205a7-3fb6-4f1c-80c0-96e387bf846f")]
        public string selectedCampus
        {
            get { return _selectedCampus; }
            set { _selectedCampus = value; }
        }

        string _selectedZone;

        /// <summary>
        /// Gets or sets the value of variable selectedZone.
        /// </summary>
        [TestVariable("5c108b40-2f20-4e8c-b979-368f1c7794d8")]
        public string selectedZone
        {
            get { return _selectedZone; }
            set { _selectedZone = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.addCampusSpanTag' at Center.", repo.ApplicationUnderTest.addCampusSpanTagInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.addCampusSpanTag.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.campusDropdown' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDropdownInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'innertext' from item 'ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance' and assigning its value to variable 'selectedCampus'.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstanceInfo, new RecordItemIndex(3));
            selectedCampus = repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance.Element.GetAttributeValueText("innertext");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstanceInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.campusDropdown' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDropdownInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.zoneDropdown' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.zoneDropdownInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.zoneDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'innertext' from item 'ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance' and assigning its value to variable 'selectedZone'.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstanceInfo, new RecordItemIndex(7));
            selectedZone = repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance.Element.GetAttributeValueText("innertext");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstanceInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.visibleDropdown_firstInstance.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.zoneDropdown' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.zoneDropdownInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.zoneDropdown.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Campus_MDC_CreateEdit.campusDescription' at Center.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDescriptionInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDescription.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$description' with focus on 'ApplicationUnderTest.Campus_MDC_CreateEdit.campusDescription'.", repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDescriptionInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.Campus_MDC_CreateEdit.campusDescription.PressKeys(description);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Content1.ButtonTagSave' at Center.", repo.ApplicationUnderTest.Content1.ButtonTagSaveInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Content1.ButtonTagSave.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(14720);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
