///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The downloadAsExcel_Grid recording.
    /// </summary>
    [TestModule("4c4ffc3d-b32e-47b7-8d18-694786282639", ModuleType.Recording, 1)]
    public partial class downloadAsExcel_Grid : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static downloadAsExcel_Grid instance = new downloadAsExcel_Grid();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public downloadAsExcel_Grid()
        {
            content1 = "";
            content2 = "";
            content3 = "";
            content4 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static downloadAsExcel_Grid Instance
        {
            get { return instance; }
        }

#region Variables

        string _content1;

        /// <summary>
        /// Gets or sets the value of variable content1.
        /// </summary>
        [TestVariable("7c0f2de5-f347-40f7-a2fb-c2fdbf7038bc")]
        public string content1
        {
            get { return _content1; }
            set { _content1 = value; }
        }

        string _content2;

        /// <summary>
        /// Gets or sets the value of variable content2.
        /// </summary>
        [TestVariable("a29bf942-fdba-4014-acbd-994ef8fa83de")]
        public string content2
        {
            get { return _content2; }
            set { _content2 = value; }
        }

        string _content3;

        /// <summary>
        /// Gets or sets the value of variable content3.
        /// </summary>
        [TestVariable("729967c7-6f8b-40cc-81c1-49e78087f2b3")]
        public string content3
        {
            get { return _content3; }
            set { _content3 = value; }
        }

        string _content4;

        /// <summary>
        /// Gets or sets the value of variable content4.
        /// </summary>
        [TestVariable("ca6dfc81-a696-49c7-a905-7834dd06ad34")]
        public string content4
        {
            get { return _content4; }
            set { _content4 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.syncfusionGridTable_headers.row1_column1_header_title' and assigning its value to variable 'content1'.", repo.ApplicationUnderTest.syncfusionGridTable_headers.row1_column1_header_titleInfo, new RecordItemIndex(0));
            content1 = repo.ApplicationUnderTest.syncfusionGridTable_headers.row1_column1_header_title.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.syncfusionGridTable_headers.row1_column2_header_title' and assigning its value to variable 'content2'.", repo.ApplicationUnderTest.syncfusionGridTable_headers.row1_column2_header_titleInfo, new RecordItemIndex(1));
            content2 = repo.ApplicationUnderTest.syncfusionGridTable_headers.row1_column2_header_title.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.syncfusionGridTable_records.row1_column1' and assigning its value to variable 'content3'.", repo.ApplicationUnderTest.syncfusionGridTable_records.row1_column1Info, new RecordItemIndex(2));
            content3 = repo.ApplicationUnderTest.syncfusionGridTable_records.row1_column1.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.syncfusionGridTable_records.row1_column2' and assigning its value to variable 'content4'.", repo.ApplicationUnderTest.syncfusionGridTable_records.row1_column2Info, new RecordItemIndex(3));
            content4 = repo.ApplicationUnderTest.syncfusionGridTable_records.row1_column2.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.button_id_dropDownButton' at Center.", repo.ApplicationUnderTest.button_id_dropDownButtonInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.button_id_dropDownButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.shareDropdown_Excel' at Center.", repo.ApplicationUnderTest.shareDropdown_ExcelInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.shareDropdown_Excel.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.confirmFileDownloaded("xlsx", content1, content2, content3, content4);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
