///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The enterEmail_ForgotPassword recording.
    /// </summary>
    [TestModule("b8375b1e-531b-435a-a40f-1b810d42e8ff", ModuleType.Recording, 1)]
    public partial class EnterEmail_ForgotPassword : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static EnterEmail_ForgotPassword instance = new EnterEmail_ForgotPassword();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnterEmail_ForgotPassword()
        {
            contactEmail = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnterEmail_ForgotPassword Instance
        {
            get { return instance; }
        }

#region Variables

        string _contactEmail;

        /// <summary>
        /// Gets or sets the value of variable contactEmail.
        /// </summary>
        [TestVariable("9adf8b6e-b3b3-4d29-aaa5-30d535a47883")]
        public string contactEmail
        {
            get { return _contactEmail; }
            set { _contactEmail = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.loginPage_ForgotPasswordButton' at Center.", repo.ApplicationUnderTest.loginPage_ForgotPasswordButtonInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.loginPage_ForgotPasswordButton.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.inputField_id_email' at Center.", repo.ApplicationUnderTest.inputField_id_emailInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.inputField_id_email.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$contactEmail' with focus on 'ApplicationUnderTest.inputField_id_email'.", repo.ApplicationUnderTest.inputField_id_emailInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.inputField_id_email.PressKeys(contactEmail);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}' with focus on 'ApplicationUnderTest.inputField_id_email'.", repo.ApplicationUnderTest.inputField_id_emailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.inputField_id_email.PressKeys("{Escape}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.buttonTagSubmit' at Center.", repo.ApplicationUnderTest.buttonTagSubmitInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.buttonTagSubmit.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
