///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The fillData_fundingSource recording.
    /// </summary>
    [TestModule("5566deb0-b86b-4980-ac0f-48d0ba0b4108", ModuleType.Recording, 1)]
    public partial class fillData_fundingSource : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static fillData_fundingSource instance = new fillData_fundingSource();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public fillData_fundingSource()
        {
            newItemName = "";
            linkedCategory = "";
            descriptionText = "test description";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static fillData_fundingSource Instance
        {
            get { return instance; }
        }

#region Variables

        string _newItemName;

        /// <summary>
        /// Gets or sets the value of variable newItemName.
        /// </summary>
        [TestVariable("c73693d1-eaaa-499d-b540-ef043e2bc48a")]
        public string newItemName
        {
            get { return _newItemName; }
            set { _newItemName = value; }
        }

        string _linkedCategory;

        /// <summary>
        /// Gets or sets the value of variable linkedCategory.
        /// </summary>
        [TestVariable("98588854-a0c7-4e3e-8ccd-2ade1527e92e")]
        public string linkedCategory
        {
            get { return _linkedCategory; }
            set { _linkedCategory = value; }
        }

        string _descriptionText;

        /// <summary>
        /// Gets or sets the value of variable descriptionText.
        /// </summary>
        [TestVariable("7001a12a-64e1-41b1-980a-2c71d4a19517")]
        public string descriptionText
        {
            get { return _descriptionText; }
            set { _descriptionText = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FundingWrapperNgStarInsertedRow.Text1' at Center.", repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.Text1Info, new RecordItemIndex(0));
            repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.Text1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$newItemName' with focus on 'ApplicationUnderTest.FundingWrapperNgStarInsertedRow.Text1'.", repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.Text1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.Text1.PressKeys(newItemName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FundingWrapperNgStarInsertedRow.MatMdcSelectMinLineMatMdcSelectP' at Center.", repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.MatMdcSelectMinLineMatMdcSelectPInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.MatMdcSelectMinLineMatMdcSelectP.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MatOption' at Center.", repo.ApplicationUnderTest.MatOptionInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.MatOption.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FundingWrapperNgStarInsertedRow.MatMdcSelectMinLineMatMdcSelectP' and assigning its value to variable 'linkedCategory'.", repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.MatMdcSelectMinLineMatMdcSelectPInfo, new RecordItemIndex(4));
            linkedCategory = repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.MatMdcSelectMinLineMatMdcSelectP.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.FundingWrapperNgStarInsertedRow.createFundingSource_description' at Center.", repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.createFundingSource_descriptionInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.createFundingSource_description.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$descriptionText' with focus on 'ApplicationUnderTest.FundingWrapperNgStarInsertedRow.createFundingSource_description'.", repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.createFundingSource_descriptionInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.FundingWrapperNgStarInsertedRow.createFundingSource_description.PressKeys(descriptionText);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
