///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The loginAsContact recording.
    /// </summary>
    [TestModule("b665cc0d-4d49-4e3f-a4e1-9a8e6af4ebc6", ModuleType.Recording, 1)]
    public partial class loginAsContact : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static loginAsContact instance = new loginAsContact();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public loginAsContact()
        {
            contactEmail = "";
            newPassword = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static loginAsContact Instance
        {
            get { return instance; }
        }

#region Variables

        string _contactEmail;

        /// <summary>
        /// Gets or sets the value of variable contactEmail.
        /// </summary>
        [TestVariable("d56f67af-9051-4643-96a9-4d8b71d7fdd0")]
        public string contactEmail
        {
            get { return _contactEmail; }
            set { _contactEmail = value; }
        }

        string _newPassword;

        /// <summary>
        /// Gets or sets the value of variable newPassword.
        /// </summary>
        [TestVariable("7b73fa3b-ebcb-4cb6-b6a6-6ea2a54e215d")]
        public string newPassword
        {
            get { return _newPassword; }
            set { _newPassword = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.loginPage_inputUserName' at Center.", repo.ApplicationUnderTest.loginPage_inputUserNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.loginPage_inputUserName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$contactEmail' with focus on 'ApplicationUnderTest.loginPage_inputUserName'.", repo.ApplicationUnderTest.loginPage_inputUserNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.loginPage_inputUserName.PressKeys(contactEmail);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}' with focus on 'ApplicationUnderTest.loginPage_inputUserName'.", repo.ApplicationUnderTest.loginPage_inputUserNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.loginPage_inputUserName.PressKeys("{Escape}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.loginPage_inputPassword' at Center.", repo.ApplicationUnderTest.loginPage_inputPasswordInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.loginPage_inputPassword.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$newPassword' with focus on 'ApplicationUnderTest.loginPage_inputPassword'.", repo.ApplicationUnderTest.loginPage_inputPasswordInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.loginPage_inputPassword.PressKeys(newPassword);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Escape}' with focus on 'ApplicationUnderTest.loginPage_inputPassword'.", repo.ApplicationUnderTest.loginPage_inputPasswordInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.loginPage_inputPassword.PressKeys("{Escape}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.loginPage_signInButton' at Center.", repo.ApplicationUnderTest.loginPage_signInButtonInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.loginPage_signInButton.Click();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
