///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateProjects_Issue recording.
    /// </summary>
    [TestModule("d1f669d0-648c-4634-96eb-026b2432eacd", ModuleType.Recording, 1)]
    public partial class validateProjects_Issue : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static validateProjects_Issue instance = new validateProjects_Issue();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateProjects_Issue()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateProjects_Issue Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.Content.Text' at 84;21.", repo.IFM360ProjectInfo.Content.TextInfo, new RecordItemIndex(0));
            repo.IFM360ProjectInfo.Content.Text.Click("84;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'IFM360ProjectInfo.Content.Text'.", repo.IFM360ProjectInfo.Content.TextInfo, new RecordItemIndex(1));
            repo.IFM360ProjectInfo.Content.Text.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.Sorting1TextLeft' at 148;22.", repo.IFM360ProjectInfo.DtTable.Sorting1TextLeftInfo, new RecordItemIndex(2));
            repo.IFM360ProjectInfo.DtTable.Sorting1TextLeft.Click("148;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTag01222025' at 180;21.", repo.IFM360ProjectInfo.DtTable.TdTag01222025Info, new RecordItemIndex(3));
            repo.IFM360ProjectInfo.DtTable.TdTag01222025.Click("180;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTag' at 155;19.", repo.IFM360ProjectInfo.DtTable.TdTagInfo, new RecordItemIndex(4));
            repo.IFM360ProjectInfo.DtTable.TdTag.Click("155;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTag1' at 144;19.", repo.IFM360ProjectInfo.DtTable.TdTag1Info, new RecordItemIndex(5));
            repo.IFM360ProjectInfo.DtTable.TdTag1.Click("144;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTag2' at 162;22.", repo.IFM360ProjectInfo.DtTable.TdTag2Info, new RecordItemIndex(6));
            repo.IFM360ProjectInfo.DtTable.TdTag2.Click("162;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTag3' at 126;25.", repo.IFM360ProjectInfo.DtTable.TdTag3Info, new RecordItemIndex(7));
            repo.IFM360ProjectInfo.DtTable.TdTag3.Click("126;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTag4' at 109;19.", repo.IFM360ProjectInfo.DtTable.TdTag4Info, new RecordItemIndex(8));
            repo.IFM360ProjectInfo.DtTable.TdTag4.Click("109;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IFM360ProjectInfo.DtTable.TdTagNo' at 55;25.", repo.IFM360ProjectInfo.DtTable.TdTagNoInfo, new RecordItemIndex(9));
            repo.IFM360ProjectInfo.DtTable.TdTagNo.Click("55;25");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
