///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateNotDeleted recording.
    /// </summary>
    [TestModule("78485bba-996e-4a40-8457-a79309106640", ModuleType.Recording, 1)]
    public partial class validateNotDeleted : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static validateNotDeleted instance = new validateNotDeleted();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateNotDeleted()
        {
            deletingItem = "";
            itemPresent = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateNotDeleted Instance
        {
            get { return instance; }
        }

#region Variables

        string _deletingItem;

        /// <summary>
        /// Gets or sets the value of variable deletingItem.
        /// </summary>
        [TestVariable("1e51fba0-68a1-46b4-9eb0-0d70e02aa3b2")]
        public string deletingItem
        {
            get { return _deletingItem; }
            set { _deletingItem = value; }
        }

        string _itemPresent;

        /// <summary>
        /// Gets or sets the value of variable itemPresent.
        /// </summary>
        [TestVariable("c29b776f-8b98-477e-9501-c95f03c480b6")]
        public string itemPresent
        {
            get { return _itemPresent; }
            set { _itemPresent = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.FaFaSpinFaSpinner'", repo.ApplicationUnderTest.FaFaSpinFaSpinnerInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.FaFaSpinFaSpinnerInfo.WaitForNotExists(30000);
            
            HelperMethodsCollection.findTextInList(repo.ApplicationUnderTest.Content1.linkedItemsList, deletingItem, ValueConverter.ArgumentFromString<bool>("wantMatch", "True"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Content1.MatExpansionPanelHeader1' at Center.", repo.ApplicationUnderTest.Content1.MatExpansionPanelHeader1Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Content1.MatExpansionPanelHeader1.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
