///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateCheckboxesAndFields_Issue_Project recording.
    /// </summary>
    [TestModule("cf8ea8e2-c77d-43fa-abc4-f559b48bdf2b", ModuleType.Recording, 1)]
    public partial class validateCheckboxesAndFields_Issue_Project : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static validateCheckboxesAndFields_Issue_Project instance = new validateCheckboxesAndFields_Issue_Project();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateCheckboxesAndFields_Issue_Project()
        {
            selectedType = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateCheckboxesAndFields_Issue_Project Instance
        {
            get { return instance; }
        }

#region Variables

        string _selectedType;

        /// <summary>
        /// Gets or sets the value of variable selectedType.
        /// </summary>
        [TestVariable("9b3415a3-9c20-451b-833f-e6c9a4ffec40")]
        public string selectedType
        {
            get { return _selectedType; }
            set { _selectedType = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // No changes yet
            Report.Log(ReportLevel.Info, "Section", "No changes yet", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.titleInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.titleInput_issues_ProjectsInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.titleInput_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.ballinCourtInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.ballinCourtInput_issues_ProjectsInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.ballinCourtInput_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.statusTextare_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.statusTextare_issues_ProjectsInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.statusTextare_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.descriptionTextare_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.descriptionTextare_issues_ProjectsInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.descriptionTextare_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_ProjectsInfo, "Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.amountInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.amountInput_issues_ProjectsInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.amountInput_issues_ProjectsInfo, "Disabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (aria-disabled='true') on item 'ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_ProjectsInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_ProjectsInfo, "aria-disabled", "true");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_ProjectsInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_ProjectsInfo, "Disabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, "Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, "Disabled", "True");
            Delay.Milliseconds(0);
            
            // Checkbox "Potential Cost Impact" : checked
            Report.Log(ReportLevel.Info, "Section", "Checkbox \"Potential Cost Impact\" : checked", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_Projects' at Center.", repo.ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_Projects.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.potentialCostImpactCheckbox_issues_ProjectsInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.amountInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.amountInput_issues_ProjectsInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.amountInput_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (aria-disabled='false') on item 'ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_ProjectsInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_ProjectsInfo, "aria-disabled", "false");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_ProjectsInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_ProjectsInfo, "Disabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, "Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, "Disabled", "True");
            Delay.Milliseconds(0);
            
            // Dropdown "Select Type" : option selected
            Report.Log(ReportLevel.Info, "Section", "Dropdown \"Select Type\" : option selected", new RecordItemIndex(19));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_Projects' at Center.", repo.ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_ProjectsInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.issueCreateEditForm_project.selectTypeDropdown_issues_Projects.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.listbox_firstOption' and assigning its value to variable 'selectedType'.", repo.ApplicationUnderTest.listbox_firstOptionInfo, new RecordItemIndex(21));
            selectedType = repo.ApplicationUnderTest.listbox_firstOption.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.listbox_firstOption' at Center.", repo.ApplicationUnderTest.listbox_firstOptionInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.listbox_firstOption.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_ProjectsInfo, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.documentIdInput_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, "Checked", "False");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, "Disabled", "True");
            Delay.Milliseconds(0);
            
            // Checkbox "Schedule Impact" : checked
            Report.Log(ReportLevel.Info, "Section", "Checkbox \"Schedule Impact\" : checked", new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_Projects' at Center.", repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_Projects.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.ScheduleImpactCheckbox_issues_ProjectsInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='False') on item 'ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_Projects'.", repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, new RecordItemIndex(29));
            Validate.AttributeEqual(repo.ApplicationUnderTest.issueCreateEditForm_project.numberOfDaysInput_issues_ProjectsInfo, "Disabled", "False");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
