///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BudgetItemAutomationIFM
{
    public partial class validateEditItem_ExistingName
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_secondRow_FirstElement(RepoItemInfo unknownInfo, string record1)
        {
        	string record2;
        	
        	try
        	{
        		Validate.Exists(unknownInfo);
        			
        		record2 = repo.ApplicationUnderTest.secondRow_FirstElement.Element.GetAttributeValueText("InnerText");
        		HelperMethodsCollection.compareStringsNotEqual(record1, record2);
        	}
        	catch(Ranorex.ElementNotFoundException)
        	{
        		
        	}
        }

        public void Validate_secondRow_FirstElement(string record1, string elementInfoItemRxPath)
        {
        	
        	Element record2Info;
        	
        	if (Host.Local.TryFindSingle(elementInfoItemRxPath, 1000, out record2Info))
        	{
        		string record2 = record2Info.GetAttributeValueText("InnerText");
        		HelperMethodsCollection.compareStringsNotEqual(record1, record2);
        	}
        }

    }
}
