///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BudgetItemAutomationIFM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The validateContactRemoval_Project recording.
    /// </summary>
    [TestModule("369b8c65-a22e-4e12-9f3c-2f2d1fc95256", ModuleType.Recording, 1)]
    public partial class validateContactRemoval_Project : ITestModule
    {
        /// <summary>
        /// Holds an instance of the BudgetItemAutomationIFMRepository repository.
        /// </summary>
        public static BudgetItemAutomationIFMRepository repo = BudgetItemAutomationIFMRepository.Instance;

        static validateContactRemoval_Project instance = new validateContactRemoval_Project();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public validateContactRemoval_Project()
        {
            contactFullName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static validateContactRemoval_Project Instance
        {
            get { return instance; }
        }

#region Variables

        string _contactFullName;

        /// <summary>
        /// Gets or sets the value of variable contactFullName.
        /// </summary>
        [TestVariable("109554e2-b2a5-42d3-92bf-889065dc3ec7")]
        public string contactFullName
        {
            get { return _contactFullName; }
            set { _contactFullName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable domain.
        /// </summary>
        [TestVariable("0e49bfa6-0c8f-4999-ad77-5babbb4e74af")]
        public string domain
        {
            get { return repo.domain; }
            set { repo.domain = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.searchBar_type_search' at Center.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.searchBar_type_search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$contactFullName' with focus on 'ApplicationUnderTest.searchBar_type_search'.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.searchBar_type_search.PressKeys(contactFullName);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.searchBar_type_search'.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.searchBar_type_search.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.waitForLoading();
            Delay.Milliseconds(0);
            
            HelperMethodsCollection.checkFirstRecord_IfExists(contactFullName, ".//div[@class='e-gridcontent']//table/tbody/tr[1]/td[1]/?/?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.searchBar_type_search' at Center.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.searchBar_type_search.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ApplicationUnderTest.searchBar_type_search'.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.ApplicationUnderTest.searchBar_type_search);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.searchBar_type_search'.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.searchBar_type_search.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ApplicationUnderTest.searchBar_type_search'.", repo.ApplicationUnderTest.searchBar_type_searchInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.searchBar_type_search.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
